### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by qazmko1029** [slzKud/bwdb_electron#1]
步骤：在搜索框输入如“1627”，按enter无效，按搜索按钮退出搜索框后列表出现搜索结果，按任意项目后连续多次弹出错误框
![2020-07-30_140603](https://user-images.githubusercontent.com/26039619/88887210-89e5dd80-d26e-11ea-91a4-5bd69acd2a63.png)

**Comment by slzKud** [comment]
问题我这边没有复现成功，请说明完整情况。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: qazmko1029<mailto:notifications@github.com>
发送时间: 2020年7月30日 14:11
收件人: slzKud/bwdb_electron<mailto:bwdb_electron@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [slzKud/bwdb_electron] 搜索功能无法使用 (#1)


步骤：在搜索框输入如“1627”，按enter无效，按搜索按钮退出搜索框后列表出现搜索结果，按任意项目后连续多次弹出错误框
[2020-07-30_140603]<https://user-images.githubusercontent.com/26039619/88887210-89e5dd80-d26e-11ea-91a4-5bd69acd2a63.png>

―

**Comment by slzKud** [comment]
不过看上去是获取build信息时发生的错误，你可以下载最新版的项目文件进行测试（release）面板

**Comment by slzKud** [comment]
已确认修复
