### ISSUE TITLE
高DPI下窗口过大，界面布局不舒服

### ISSUE THREAD

**Issue by qazmko1029** [slzKud/bwdb_electron#2]
具体表现为主窗口中各种间距过大，图片窗口中按钮图案和边框间距过大。

**Comment by slzKud** [comment]
抄送，已关注此问题。最近将专门进行修复

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: qazmko1029<mailto:notifications@github.com>
发送时间: 2020年7月30日 14:21
收件人: slzKud/bwdb_electron<mailto:bwdb_electron@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [slzKud/bwdb_electron] 高DPI下窗口过大，界面布局不舒服 (#2)


具体表现为主窗口中各种间距过大，图片窗口中按钮图案和边框间距过大。

―

**Comment by slzKud** [comment]
https://github.com/slzKud/bwdb_electron/commit/520099fa5f9c6360f54e4df74c03a4c220ab3319
已尝试修复

**Comment by slzKud** [comment]
https://github.com/slzKud/bwdb_electron/commit/4082ba43cad52917e8ddb1b53550faf5fa8a2e92
已解决，Closed
